# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 11:39
from __future__ import unicode_literals
from django.db.models.signals import post_init

from django.db import migrations

def create_singleton_objects(apps, schema_editor):
    app_name = "packet"

    from packet.model_classes.PacketState import ActivatedPacket, DeactivatedPacket, IncompletePacket
    ActivatedPacket().save()
    ActivatedPacket.objects.all()[0].setName()
    IncompletePacket().save()
    IncompletePacket.objects.all()[0].setName()
    DeactivatedPacket().save()
    DeactivatedPacket.objects.all()[0].setName()

    PacketCatalog = apps.get_model(app_name, "PacketCatalog")
    PacketCatalog().save()

class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_singleton_objects),
    ]
