# sales_strategy_properties:
sales_strategy_properties__compositebestfor = 'store'
sales_strategy_properties__morepacketsstrategy = True
sales_strategy_properties__studentcustomerstrategy = True

# morePacketsStrategy_properties:
morePacketsStrategy_properties__percentage_of_discount = 15
morePacketsStrategy_properties__min_number_of_packets = 2

# studentCustomerStrategy_properties:
studentCustomerStrategy_properties__percentage_of_discount = 5