# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(null=True)),
                ('endDate', models.DateTimeField(null=True)),
                ('packets', models.ManyToManyField(related_name='subscriptions', to='packet.Packet')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=b'Undefined', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSubscription',
            fields=[
                ('subscriptionstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subscription.SubscriptionState')),
            ],
            bases=('subscription.subscriptionstate',),
        ),
        migrations.CreateModel(
            name='ExpiredSubscription',
            fields=[
                ('subscriptionstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subscription.SubscriptionState')),
            ],
            bases=('subscription.subscriptionstate',),
        ),
        migrations.CreateModel(
            name='InactiveSubscription',
            fields=[
                ('subscriptionstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subscription.SubscriptionState')),
            ],
            bases=('subscription.subscriptionstate',),
        ),
        migrations.AddField(
            model_name='subscription',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.SubscriptionState', to_field=b'name'),
        ),
    ]
