# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 11:39
from __future__ import unicode_literals
from django.db.models.signals import post_init

from django.db import migrations

def create_singleton_objects(apps, schema_editor):
    app_name = "subscription"

    from subscription.model_classes.SubscriptionState import ActiveSubscription, InactiveSubscription, ExpiredSubscription
    ActiveSubscription().save()
    ActiveSubscription.objects.all()[0].setName()
    InactiveSubscription().save()
    InactiveSubscription.objects.all()[0].setName()
    ExpiredSubscription().save()
    ExpiredSubscription.objects.all()[0].setName()


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_singleton_objects),
    ]
