# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 11:39
from __future__ import unicode_literals
from django.db.models.signals import post_init

from django.db import migrations

def create_singleton_objects(apps, schema_editor):
    app_name = "sale"


    from sale.model_classes.SaleState import CompletedSale, CancelledSale, IncompleteSale
    CompletedSale().save()
    CompletedSale.objects.all()[0].setName()
    CancelledSale().save()
    CancelledSale.objects.all()[0].setName()
    IncompleteSale().save()
    IncompleteSale.objects.all()[0].setName()


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_singleton_objects),
    ]
